### ISSUE TITLE
Error on boot up from celery/Redis

### ISSUE THREAD

**Issue by jlfwong** [UWFlow/rmc#286]
When I run `make local` inside the Docker container, I get this:

```
[2016-06-27 19:46:39,990: ERROR/MainProcess] Unrecoverable error: TypeError("__init__() got an unexpected keyword argument 'socket_connect_timeout'",)                                              [2/1884]
Traceback (most recent call last):
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 212, in start
    self.blueprint.start(self)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/bootsteps.py", line 373, in start
    return self.obj.start()
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 270, in start
    blueprint.start(self)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 467, in start
    c.connection = c.connect()
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 366, in connect
    callback=maybe_shutdown,
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 464, in __init__
    self.client.info()
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 908, in client
    return self._create_client(async=True)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 861, in _create_client
    return self.AsyncClient(connection_pool=self.async_pool)
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 882, in __init__
    self.connection = self.connection_pool.get_connection('_')
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/redis/connection.py", line 381, in get_connection
    connection = self.make_connection()
  File "/root/.virtualenv/rmc/local/lib/python2.7/site-packages/redis/connection.py", line 390, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'socket_connect_timeout'
```

Bootup seems to continue normally, but I haven't checked yet to see if Redis or Celery is actually working inside the container.

**Comment by JGulbronson** [comment]
We should be able to fix this by pinning the Redis version used int he container. The server uses 2.6.3, so ideally we use that.
